.\" Manpage for scanpf.
.\" Contact contact@digitalleaves.com for comments or help.
.TH man 1 "28 Apr 2020" "1.0" "scanpf man page"
.SH NAME
scanpf \- simple hello world example application
.SH SYNOPSIS
scanpf
.SH DESCRIPTION
scanpf todo ...
.SH OPTIONS
scanpf does not take any arguments.
.SH BUGS
No known bugs.
.SH AUTHOR
Brian Preston (brian8181@gmail.com)